services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./Project:/var/www/html/
    depends_on:
      - mysql
    networks:
      - app-network
    
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: mysqlpassword
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-laravel
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 1024M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge